In [1]:
import pandas as pd
import numpy as np

In [2]:
college=pd.read_csv('data/college.csv',index_col='INSTNM')

In [3]:
college.head()

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
Alabama A & M University,Normal,AL,1.0,0.0,0.0,0,424.0,420.0,0.0,4206.0,...,0.0000,0.0059,0.0138,0.0656,1,0.7356,0.8284,0.1049,30300,33888
University of Alabama at Birmingham,Birmingham,AL,0.0,0.0,0.0,0,570.0,565.0,0.0,11383.0,...,0.0368,0.0179,0.0100,0.2607,1,0.3460,0.5214,0.2422,39700,21941.5
Amridge University,Montgomery,AL,0.0,0.0,0.0,1,NaN,NaN,1.0,291.0,...,0.0000,0.0000,0.2715,0.4536,1,0.6801,0.7795,0.8540,40100,23370
University of Alabama in Huntsville,Huntsville,AL,0.0,0.0,0.0,0,595.0,590.0,0.0,5451.0,...,0.0172,0.0332,0.0350,0.2146,1,0.3072,0.4596,0.2640,45500,24097
Alabama State University,Montgomery,AL,1.0,0.0,0.0,0,425.0,430.0,0.0,4811.0,...,0.0098,0.0243,0.0137,0.0892,1,0.7347,0.7554,0.1270,26600,33118.5

In [22]:
college.shape[0]

7535

In [5]:
grouped=college.groupby('STABBR')
grouped.ngroups == len(list(grouped.groups.keys())) == college.STABBR.nunique()

True

In [6]:
# checking minority majority occurance with .filter() method

In [7]:
def check_minority(df,threshold=.5):
    minority_pct=1-df.UGDS_WHITE
    total_minority=(df.UGDS*minority_pct).sum()
    total_ugds=df.UGDS.sum()
    total_minority_pct=total_minority/total_ugds
    return total_minority_pct > threshold

In [8]:
# as seen below, new table shape differs significantly, comparing to origin size

In [21]:
college_filtered=grouped.filter(check_minority)
college_filtered.shape[0]

3028

In [10]:
# equivalent method with .apply() and boolean indexing

In [11]:
def return_pct_minority(df):
    minority_pct=1-df.UGDS_WHITE
    total_minority=(df.UGDS*minority_pct).sum()
    total_ugds=df.UGDS.sum()
    return total_minority/total_ugds

In [12]:
pct_apply=grouped.apply(return_pct_minority)

In [34]:
["%s : %.2f" % (k,v) for k,v in pct_apply.items()][:10]

['AK : 0.49',
 'AL : 0.40',
 'AR : 0.33',
 'AS : 1.00',
 'AZ : 0.57',
 'CA : 0.71',
 'CO : 0.39',
 'CT : 0.45',
 'DC : 0.60',
 'DE : 0.42']

In [14]:
college['MINOR_MAJOR']=college.STABBR.map(pct_apply.to_dict())

In [15]:
college.head()

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP,MINOR_MAJOR
INSTNM,,,,,,,,,,,,,,,,,,,,,
Alabama A & M University,Normal,AL,1.0,0.0,0.0,0,424.0,420.0,0.0,4206.0,...,0.0059,0.0138,0.0656,1,0.7356,0.8284,0.1049,30300,33888,0.40076
University of Alabama at Birmingham,Birmingham,AL,0.0,0.0,0.0,0,570.0,565.0,0.0,11383.0,...,0.0179,0.0100,0.2607,1,0.3460,0.5214,0.2422,39700,21941.5,0.40076
Amridge University,Montgomery,AL,0.0,0.0,0.0,1,NaN,NaN,1.0,291.0,...,0.0000,0.2715,0.4536,1,0.6801,0.7795,0.8540,40100,23370,0.40076
University of Alabama in Huntsville,Huntsville,AL,0.0,0.0,0.0,0,595.0,590.0,0.0,5451.0,...,0.0332,0.0350,0.2146,1,0.3072,0.4596,0.2640,45500,24097,0.40076
Alabama State University,Montgomery,AL,1.0,0.0,0.0,0,425.0,430.0,0.0,4811.0,...,0.0243,0.0137,0.0892,1,0.7347,0.7554,0.1270,26600,33118.5,0.40076

In [36]:
college.query('MINOR_MAJOR > 0.5').shape[0] == college_filtered.shape[0]

True